from pathlib import Path
import unittest


WEB_INDEX = Path(__file__).resolve().parents[1] / "gui" / "web" / "index.html"
VERIFY_DMG_BACKEND = Path(__file__).resolve().parents[1] / "scripts" / "verify_dmg_backend.sh"


class TestWebUI(unittest.TestCase):
    def test_web_ui_renders_product_actions_and_safe_fix_commands(self):
        html = WEB_INDEX.read_text(encoding="utf-8")

        self.assertIn("renderActions(explanation)", html)
        self.assertIn("buildReportViewModel", html)
        self.assertIn("renderReportSummary", html)
        self.assertIn("showFileModeBlocked", html)
        self.assertIn("window.location.protocol === 'file:'", html)
        self.assertIn("请从 Netfix App 打开", html)
        self.assertIn("不能自己启动本地诊断引擎", html)
        self.assertIn("正常使用不需要终端、Python 命令或手输 127.0.0.1", html)
        self.assertIn("data-summary-action", html)
        self.assertIn("下一步：按你的真实目标处理", html)
        self.assertIn("userFacingStatusText", html)
        self.assertIn("operationInProgress", html)
        self.assertIn("检查中...", html)
        self.assertIn("正在检查连接路径", html)
        self.assertIn("ChatGPT 网页打不开", html)
        self.assertIn("Codex / OpenAI 报错", html)
        self.assertIn("GitHub / Copilot 连不上", html)
        self.assertIn("需要时再用", html)
        self.assertIn('id="ai-panel" class="panel hidden"', html)
        self.assertIn('id="proxy-panel" class="panel hidden"', html)
        self.assertIn('id="log-panel" class="panel hidden"', html)
        self.assertIn("manual_steps", html)
        self.assertIn("needs_confirm", html)
        self.assertIn("fix', '--all', '--yes', '--report'", html)
        self.assertIn("fix', '--issue', actionId, '--dry-run'", html)
        self.assertIn("fix', '--issue', actionId, '--yes', '--report'", html)
        self.assertIn("/llm/providers", html)
        self.assertIn("/llm/chain-readiness", html)
        self.assertIn("/llm/chain-test", html)
        self.assertIn("/llm/import-deepseek-sidecar-key", html)
        self.assertIn("llm-chain-readiness", html)
        self.assertIn("llm-enabled", html)
        self.assertIn("llm-key-form", html)
        self.assertIn('autocomplete="username"', html)
        self.assertIn('autocomplete="new-password"', html)
        self.assertIn("导入 DeepSeek 密钥", html)
        self.assertIn("IMPORT_DEEPSEEK_SIDECAR_KEY", html)
        self.assertIn("importDeepSeekSidecarKey", html)
        self.assertIn("启用云端 AI 解释", html)
        self.assertIn("renderLLMChainReadiness", html)
        self.assertIn("renderProviderAdapterEvidence", html)
        self.assertIn("official_docs", html)
        self.assertIn("metadata_checked_at", html)
        self.assertIn("max_tokens_field", html)
        self.assertIn("官方文档核验", html)
        self.assertIn("请求字段", html)
        self.assertIn("renderLLMChainTest", html)
        self.assertIn("testLLMChain", html)
        self.assertIn("renderLLMBudgetStatus", html)
        self.assertIn("remaining_requests", html)
        self.assertIn("remaining_image_requests", html)
        self.assertIn("llm-budget-persist-ledger", html)
        self.assertIn("persist_usage_ledger: document.getElementById('llm-budget-persist-ledger').checked", html)
        self.assertIn("跨重启保留本地计数", html)
        self.assertIn("TEST_LLM_CHAIN", html)
        self.assertIn("${data.error ? `<div class=\"muted\">${escapeHtml(data.error)}</div>` : ''}", html)
        self.assertIn("测试链路", html)
        self.assertIn("data-select-llm-provider", html)
        self.assertIn("selectLLMProviderForKey", html)
        self.assertIn("配置密钥", html)
        self.assertIn("netfix_llm_chain_readiness.v1", html)
        self.assertIn("Keychain", html)
        self.assertIn("/explain_llm", html)
        self.assertIn("llm-question", html)
        self.assertIn("llm-images", html)
        self.assertIn('accept="image/png,image/jpeg,image/webp,image/gif"', html)
        self.assertIn("const allowedImageTypes = new Set(['image/png', 'image/jpeg', 'image/webp', 'image/gif']);", html)
        self.assertIn("只支持 PNG、JPEG、WebP 或 GIF", html)
        self.assertIn("llm-image-preview", html)
        self.assertIn("llm-upload-confirmed", html)
        self.assertIn("llm-image-question-enabled", html)
        self.assertIn("llm-budget-enabled", html)
        self.assertIn("llm-budget-hourly", html)
        self.assertIn("llm-budget-image-hourly", html)
        self.assertIn("max_requests_per_hour", html)
        self.assertIn("max_image_requests_per_hour", html)
        self.assertIn("handleAIImageSelection", html)
        self.assertIn("readFileAsDataURL", html)
        self.assertIn("renderAIImagePreview", html)
        self.assertIn("会剥离图片文件元数据", html)
        self.assertIn("不会自动识别或打码图片里的文字", html)
        self.assertIn("mode: images.length ? 'image_question' : 'explain'", html)
        self.assertIn("images,", html)
        self.assertIn("fallback_reason_label", html)
        self.assertIn("image_question: document.getElementById('llm-image-question-enabled').checked", html)
        self.assertIn("enabled: document.getElementById('llm-enabled').checked", html)
        self.assertIn("api_key_account: document.getElementById('llm-provider').value", html)
        self.assertIn("vision_chain: ['minimax', 'moonshot_kimi', 'qwen']", html)
        self.assertNotIn("prompt('你想问当前报告什么？'", html)
        self.assertIn("/proxy/parse", html)
        self.assertIn("/proxy/import-preview", html)
        self.assertIn("importProxyPreview", html)
        self.assertIn("renderProxyImportPreview", html)
        self.assertIn("data-use-proxy-line", html)
        self.assertIn("data-save-proxy-line", html)
        self.assertIn("saveProxyImportCandidate", html)
        self.assertIn("保存并看护", html)
        self.assertIn("sourceProxyLine", html)
        self.assertIn("批量预检", html)
        self.assertIn("netfix_proxy_import_preview.v1", html)
        self.assertIn("/proxy/validate", html)
        self.assertIn("/validate`", html)
        self.assertIn("/proxy/validation-targets", html)
        self.assertIn("proxy-target-profile", html)
        self.assertIn("proxy-start-monitor-on-save", html)
        self.assertIn("保存后自动看护", html)
        self.assertIn("start_monitor: document.getElementById('proxy-start-monitor-on-save').checked", html)
        self.assertIn("saveProxyProfileInput", html)
        self.assertIn("正在保存并开始持续检查", html)
        self.assertIn("monitor_interval: 60", html)
        self.assertIn("renderProxyProfileRow", html)
        self.assertIn("profiles.slice(0, 5)", html)
        self.assertIn("查看其余 ${hiddenProfiles.length} 条线路", html)
        self.assertIn("默认显示最近 5 条", html)
        self.assertIn("loadProxyValidationTargets", html)
        self.assertIn("target_profile", html)
        self.assertIn("const target_profile = document.getElementById('proxy-target-profile').value || 'baseline';", html)
        self.assertIn("检查场景", html)
        self.assertIn("验证有风险", html)
        self.assertIn("AI / 开发工具", html)
        self.assertIn("/proxy/monitor", html)
        self.assertIn("/proxy/monitor/start", html)
        self.assertIn("/proxy/monitor/stop", html)
        self.assertIn("已保存自动恢复配置", html)
        self.assertIn("/proxy/bridge/recover", html)
        self.assertIn("/settings/proxy-bridge", html)
        self.assertIn("proxy-bridge-auto-restart", html)
        self.assertIn("loadProxyBridgeSettings", html)
        self.assertIn("saveProxyBridgeSettings", html)
        self.assertIn("重启时自动恢复上次本机转发", html)
        self.assertIn("不会静默改写系统网络设置", html)
        self.assertIn("auto_restart_enabled", html)
        self.assertIn("auto_restart", html)
        self.assertIn("已自动恢复本机转发", html)
        self.assertIn("renderProxyBridgeLifecycle", html)
        self.assertIn("renderProxyBridgeStartupCheck", html)
        self.assertIn("data.lifecycle", html)
        self.assertIn("data.startup_check", html)
        self.assertIn("netfix_proxy_bridge_lifecycle.v1", html)
        self.assertIn("netfix_proxy_bridge_startup_check.v1", html)
        self.assertIn("启动时本机转发检查", html)
        self.assertIn("当前路径依赖 Netfix 本机转发", html)
        self.assertIn("RESTORE_STALE_PROXY_BRIDGE", html)
        self.assertIn("include_identity: true", html)
        self.assertIn("renderIdentityReport", html)
        self.assertIn("出口身份与泄漏风险", html)
        self.assertIn("后台看护", html)
        self.assertIn("开始看护", html)
        self.assertIn("data-delete-profile", html)
        self.assertIn("deleteProxyProfile", html)
        self.assertIn("删除线路", html)
        self.assertIn("data-replace-profile", html)
        self.assertIn("replaceProxyProfile", html)
        self.assertIn("/replace`", html)
        self.assertIn("更新凭据", html)
        self.assertIn("粘贴新的线路凭据", html)
        self.assertIn("repair_actions", html)
        self.assertIn("renderProxyRepairActions", html)
        self.assertIn("修复建议", html)
        self.assertIn("handleProxyRepairAction", html)
        self.assertIn("data-repair-action", html)
        self.assertIn("replace_profile_credentials", html)
        self.assertIn("export_profile", html)
        self.assertIn("最近请求", html)
        self.assertIn("本机其它进程也可能使用该端口", html)
        self.assertIn("recent_clients", html)
        self.assertIn("request_count", html)
        self.assertIn("data-export-profile", html)
        self.assertIn("renderProxyExport", html)
        self.assertIn("netfix_proxy_client_package.v1", html)
        self.assertIn("客户端配置包", html)
        self.assertIn("recommended_format", html)
        self.assertIn("按文件名复制到目标客户端", html)
        self.assertIn("renderProxyDecision", html)
        self.assertIn("renderProxyOperation", html)
        self.assertIn("deployment_decision", html)
        self.assertIn("requires_netfix_running", html)
        self.assertIn("本机转发", html)
        self.assertIn("需要本机转发的线路会通过 127.0.0.1 应用", html)
        self.assertIn("MiniMax", html)
        self.assertIn("monitor_persisted_cleared", html)
        self.assertIn("重启自动恢复配置已清理", html)
        self.assertIn("/export", html)
        self.assertIn("secret_placeholder", html)
        self.assertIn("&lt;password&gt;", html)
        self.assertIn("target.innerHTML = renderProxyOperation(res)", html)
        self.assertIn("target.innerHTML = renderProxyRollback(res)", html)
        self.assertNotIn("target.textContent = JSON.stringify(res, null, 2)", html)
        self.assertNotIn("__NETFIX_API_TOKEN__", html)
        self.assertNotIn("X-Netfix-Token", html)
        self.assertNotIn("report: lastReport", html)
        self.assertIn("credentials: 'same-origin'", html)
        self.assertIn("/logs", html)
        self.assertIn('id="btn-open-logs"', html)
        self.assertIn('onclick="openLogs()"', html)
        self.assertIn('id="btn-refresh-logs"', html)
        self.assertIn('role="status"', html)
        self.assertIn('aria-live="polite"', html)
        self.assertIn("function openLogs()", html)
        self.assertIn("panel.classList.remove('hidden')", html)
        self.assertIn("scrollIntoView({ behavior: 'smooth', block: 'start' })", html)
        self.assertIn("target.textContent = '正在读取运行记录...'", html)
        self.assertIn('id="recovery-panel"', html)
        self.assertIn('role="alert"', html)
        self.assertIn('onclick="retryFailedJob()"', html)
        self.assertIn('onclick="copyRecoveryDetail()"', html)
        self.assertIn("function showJobRecovery", html)
        self.assertIn("function retryFailedJob()", html)
        self.assertIn("function copyRecoveryDetail()", html)
        self.assertIn("navigator.clipboard.writeText", html)
        self.assertIn("lastFailedJob = { command, timeout, label, onDone };", html)
        self.assertNotIn("function toggleLog()", html)
        self.assertIn("DeepSeek", html)
        self.assertIn("persist-proxy-identity-report", html)
        self.assertIn("persist_proxy_identity_report", html)
        self.assertIn("保存完整线路身份记录", html)
        self.assertNotIn("执行 Tier 1 修复", html)
        self.assertNotIn("开始急诊", html)
        self.assertNotIn("导入 DeepSeek 侧车 Key", html)

    def test_dmg_backend_smoke_verifies_web_console_entrypoint(self):
        script = VERIFY_DMG_BACKEND.read_text(encoding="utf-8")

        self.assertIn('WEB_HTML="$(curl -fsS "http://127.0.0.1:${PORT}/")"', script)
        self.assertIn('[[ "${WEB_HTML}" == *"btn-open-logs"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"openLogs()"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"recovery-panel"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"renderLLMChainReadiness"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"testLLMChain"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"TEST_LLM_CHAIN"* ]]', script)
        self.assertIn('"command":["services","--group","ai"]', script)
        self.assertIn("bundled backend /run still invoked netfix.cli as a CLI argument", script)
        self.assertIn("bundled backend /run is missing the idna codec", script)
        self.assertIn('/llm/chain-readiness', script)
        self.assertIn('/llm/chain-test', script)
        self.assertIn('"netfix_llm_chain_readiness.v1"', script)
        self.assertIn('[[ "${WEB_HTML}" == *"renderProxyBridgeLifecycle"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"renderProxyBridgeStartupCheck"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"proxy-bridge-auto-restart"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"importProxyPreview"* ]]', script)
        self.assertIn('[[ "${WEB_HTML}" == *"netfix_proxy_import_preview.v1"* ]]', script)
        self.assertIn('/settings/proxy-bridge', script)
        self.assertIn('proxy_bridge_auto_restart_default', script)
        self.assertIn('/proxy/import-preview', script)
        self.assertIn('real-secret-123', script)
        self.assertIn('proxy import preview leaked the provider password', script)
        self.assertIn('/proxy/profiles/${PROFILE_ID}/export', script)
        self.assertIn('/proxy/profiles/${PROFILE_ID}/replace', script)
        self.assertIn('netfix_proxy_client_package.v1', script)
        self.assertIn('proxy_client_package', script)
        self.assertIn('proxy_profile_replace', script)
        self.assertIn('README.md', script)
        self.assertIn('.sing-box.json', script)
        self.assertIn('BRIDGE_JSON="$(curl -fsS -H "X-Netfix-Token: ${TOKEN}" "http://127.0.0.1:${PORT}/proxy/bridge")"', script)
        self.assertIn('netfix_proxy_bridge_lifecycle.v1', script)
        self.assertIn('netfix_proxy_bridge_startup_check.v1', script)


if __name__ == "__main__":
    unittest.main()
